In [18]:
#import pandas as pd
#import matplotlib.pyplot as plt 
#food = pd.read_csv("~/Downloads/Classes/Sophomore Year/Spring/Cs 130/Project/cs130-project/food.csv")
#food.Category

In [17]:
#import pandas as pd
#food = pd.read_csv("~/Downloads/Classes/Sophomore Year/Spring/Cs 130/Project/cs130-project/food.csv")
#food.sort_values(by ="Fiber", ascending = False).head()

In [30]:
import pandas as pd
import matplotlib.pyplot as plt 
food = pd.read_csv("food.csv")
#making a function that looks at all of the dairy 
food.head()

,Category(2),Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major MineralsPhosphorus,Major MineralsPotassium,Major MineralsSodium,Major MineralsZinc,VitaminsVitamin A - RAE,VitaminsVitamin B12,VitaminsVitamin B6,VitaminsVitamin C,VitaminsVitamin E,VitaminsVitamin K
0,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
1,Buttermilk,"Buttermilk, whole",11115300,0,7,0,4.88,11,14.6,0.0,...,85,135,105,0.38,47,0.46,0.036,0.0,0.07,0.3
2,Goat's milk,"Goat's milk, whole",11116000,0,7,0,4.45,11,16.0,0.0,...,111,204,50,0.30,57,0.07,0.046,1.3,0.07,0.3
3,Soy milk,Soy milk,11320000,0,2,0,4.92,0,23.6,0.2,...,43,122,47,0.26,55,0.85,0.031,0.0,0.11,3.0
4,Almond milk,"Almond milk, sweetened",11350000,0,0,0,5.24,0,3.0,0.2,...,9,64,69,0.06,86,0.00,0.000,0.0,2.70,0.0

In [46]:
#food.info()

In [47]:
#food.describe()

In [39]:
food.columns

Index(['Category(2)', 'Description', 'Nutrient Data Bank Number',
       'Alpha Carotene', 'Beta Carotene', 'Beta Cryptoxanthin', 'Carbohydrate',
       'Cholesterol', 'Choline', 'Fiber', 'Lutein and Zeaxanthin', 'Lycopene',
       'Niacin', 'Protein', 'Retinol', 'Riboflavin', 'Selenium', 'Sugar Total',
       'Thiamin', 'Water', 'FatMonosaturated Fat', 'FatPolysaturated Fat',
       'FatSaturated Fat', 'FatTotal Lipid', 'Major MineralsCalcium',
       'Major MineralsCopper', 'Major MineralsIron', 'Major MineralsMagnesium',
       'Major MineralsPhosphorus', 'Major MineralsPotassium',
       'Major MineralsSodium', 'Major MineralsZinc', 'VitaminsVitamin A - RAE',
       'VitaminsVitamin B12', 'VitaminsVitamin B6', 'VitaminsVitamin C',
       'VitaminsVitamin E', 'VitaminsVitamin K'],
      dtype='object')

In [37]:
food.index

RangeIndex(start=0, stop=1671, step=1)

In [42]:
#Using this as a reference for later for coloums 
food[["Category(2)", "Description"]]

,Category(2),Description
0,Milk,"Milk, whole"
1,Buttermilk,"Buttermilk, whole"
2,Goat's milk,"Goat's milk, whole"
3,Soy milk,Soy milk
4,Almond milk,"Almond milk, sweetened"
...,...,...
1666,Tomatoes as ingredient in omelet,Tomatoes as ingredient in omelet
1667,Other vegetables as ingredient in omelet,Other vegetables as ingredient in omelet
1668,Vegetables as ingredient in curry,Vegetables as ingredient in curry
1669,Sauce as ingredient in hamburgers,Sauce as ingredient in hamburgers
1670,Industrial oil as ingredient in food,Industrial oil as ingredient in food

In [67]:
food.head()

,Category(2),Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major MineralsPhosphorus,Major MineralsPotassium,Major MineralsSodium,Major MineralsZinc,VitaminsVitamin A - RAE,VitaminsVitamin B12,VitaminsVitamin B6,VitaminsVitamin C,VitaminsVitamin E,VitaminsVitamin K
0,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
1,Buttermilk,"Buttermilk, whole",11115300,0,7,0,4.88,11,14.6,0.0,...,85,135,105,0.38,47,0.46,0.036,0.0,0.07,0.3
2,Goat's milk,"Goat's milk, whole",11116000,0,7,0,4.45,11,16.0,0.0,...,111,204,50,0.30,57,0.07,0.046,1.3,0.07,0.3
3,Soy milk,Soy milk,11320000,0,2,0,4.92,0,23.6,0.2,...,43,122,47,0.26,55,0.85,0.031,0.0,0.11,3.0
4,Almond milk,"Almond milk, sweetened",11350000,0,0,0,5.24,0,3.0,0.2,...,9,64,69,0.06,86,0.00,0.000,0.0,2.70,0.0

In [64]:
#testing for row checking
food.iloc[0]["Category(2)"]

'Milk'

In [102]:
#making a function that looks at all of the dairy 
def milk():
    return food[(food["Category(2)"].str.contains("Milk"))| food["Category(2)"].str.contains("milk") |  food["Category(2)"].str.contains("Cheese") | food["Category(2)"].str.contains("Yogurt") | (food["Description"].str.contains("milk")) & (food["Category(2)"] != "Grits") & (food["Category(2)"] != "Rice") & (food["Category(2)"] != "Oatmeal") ]
milk()

,Category(2),Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major MineralsPhosphorus,Major MineralsPotassium,Major MineralsSodium,Major MineralsZinc,VitaminsVitamin A - RAE,VitaminsVitamin B12,VitaminsVitamin B6,VitaminsVitamin C,VitaminsVitamin E,VitaminsVitamin K
0,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
1,Buttermilk,"Buttermilk, whole",11115300,0,7,0,4.88,11,14.6,0.0,...,85,135,105,0.38,47,0.46,0.036,0.0,0.07,0.3
2,Goat's milk,"Goat's milk, whole",11116000,0,7,0,4.45,11,16.0,0.0,...,111,204,50,0.30,57,0.07,0.046,1.3,0.07,0.3
3,Soy milk,Soy milk,11320000,0,2,0,4.92,0,23.6,0.2,...,43,122,47,0.26,55,0.85,0.031,0.0,0.11,3.0
4,Almond milk,"Almond milk, sweetened",11350000,0,0,0,5.24,0,3.0,0.2,...,9,64,69,0.06,86,0.00,0.000,0.0,2.70,0.0
5,Rice milk,Rice milk,11360000,0,0,0,9.17,0,2.1,0.3,...,56,27,39,0.13,63,0.63,0.039,0.0,0.47,0.2
6,Coconut milk,Coconut milk,11370000,0,0,0,2.92,0,0.0,0.0,...,0,19,19,0.00,63,0.63,0.000,0.0,0.00,0.0
7,Yogurt,"Yogurt, NFS",11400000,0,2,0,7.04,6,15.2,0.0,...,144,234,70,0.89,14,0.56,0.049,0.8,0.03,0.2
8,Cheese,"Cheese, NFS",14010000,0,99,9,5.00,91,24.2,0.0,...,582,164,904,3.09,298,1.24,0.091,0.0,0.79,2.7

In [101]:
#making a Function looking for meats