In [31]:
#import pandas as pd
#import matplotlib.pyplot as plt 
#food = pd.read_csv("~/Downloads/Classes/Sophomore Year/Spring/Cs 130/Project/cs130-project/food.csv")
#food.Category

In [32]:
#import pandas as pd
#food = pd.read_csv("~/Downloads/Classes/Sophomore Year/Spring/Cs 130/Project/cs130-project/food.csv")
#food.sort_values(by ="Fiber", ascending = False).head()

In [33]:
import pandas as pd
import matplotlib.pyplot as plt 
food = pd.read_csv("food.csv")
#making a function that looks at all of the dairy 
food.head()

,Category,Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major Minerals.Phosphorus,Major Minerals.Potassium,Major Minerals.Sodium,Major Minerals.Zinc,Vitamins.Vitamin A - RAE,Vitamins.Vitamin B12,Vitamins.Vitamin B6,Vitamins.Vitamin C,Vitamins.Vitamin E,Vitamins.Vitamin K
0,Milk,"Milk, human",11000000,0,7,0,6.89,14,16.0,0.0,...,14,51,17,0.17,61,0.05,0.011,5.0,0.08,0.3
1,Milk,"Milk, NFS",11100000,0,4,0,4.87,8,17.9,0.0,...,103,157,39,0.42,59,0.56,0.060,0.1,0.03,0.2
2,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
3,Milk,"Milk, low sodium, whole",11111100,0,7,0,4.46,14,16.0,0.0,...,86,253,3,0.38,29,0.36,0.034,0.9,0.08,0.3
4,Milk,"Milk, calcium fortified, whole",11111150,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3

In [34]:
#food.info()

In [35]:
#food.describe()

In [36]:
food.columns

Index(['Category', 'Description', 'Nutrient Data Bank Number',
       'Alpha Carotene', 'Beta Carotene', 'Beta Cryptoxanthin', 'Carbohydrate',
       'Cholesterol', 'Choline', 'Fiber', 'Lutein and Zeaxanthin', 'Lycopene',
       'Niacin', 'Protein', 'Retinol', 'Riboflavin', 'Selenium', 'Sugar Total',
       'Thiamin', 'Water', 'Fat.Monosaturated Fat', 'Fat.Polysaturated Fat',
       'Fat.Saturated Fat', 'Fat.Total Lipid', 'Major Minerals.Calcium',
       'Major Minerals.Copper', 'Major Minerals.Iron',
       'Major Minerals.Magnesium', 'Major Minerals.Phosphorus',
       'Major Minerals.Potassium', 'Major Minerals.Sodium',
       'Major Minerals.Zinc', 'Vitamins.Vitamin A - RAE',
       'Vitamins.Vitamin B12', 'Vitamins.Vitamin B6', 'Vitamins.Vitamin C',
       'Vitamins.Vitamin E', 'Vitamins.Vitamin K'],
      dtype='object')

In [37]:
food.index

RangeIndex(start=0, stop=7083, step=1)

In [38]:
#Using this as a reference for later for coloums 
food[["Category", "Description"]]

,Category,Description
0,Milk,"Milk, human"
1,Milk,"Milk, NFS"
2,Milk,"Milk, whole"
3,Milk,"Milk, low sodium, whole"
4,Milk,"Milk, calcium fortified, whole"
...,...,...
7078,Tomatoes as ingredient in omelet,Tomatoes as ingredient in omelet
7079,Other vegetables as ingredient in omelet,Other vegetables as ingredient in omelet
7080,Vegetables as ingredient in curry,Vegetables as ingredient in curry
7081,Sauce as ingredient in hamburgers,Sauce as ingredient in hamburgers
7082,Industrial oil as ingredient in food,Industrial oil as ingredient in food

In [39]:
food.head()

,Category,Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major Minerals.Phosphorus,Major Minerals.Potassium,Major Minerals.Sodium,Major Minerals.Zinc,Vitamins.Vitamin A - RAE,Vitamins.Vitamin B12,Vitamins.Vitamin B6,Vitamins.Vitamin C,Vitamins.Vitamin E,Vitamins.Vitamin K
0,Milk,"Milk, human",11000000,0,7,0,6.89,14,16.0,0.0,...,14,51,17,0.17,61,0.05,0.011,5.0,0.08,0.3
1,Milk,"Milk, NFS",11100000,0,4,0,4.87,8,17.9,0.0,...,103,157,39,0.42,59,0.56,0.060,0.1,0.03,0.2
2,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
3,Milk,"Milk, low sodium, whole",11111100,0,7,0,4.46,14,16.0,0.0,...,86,253,3,0.38,29,0.36,0.034,0.9,0.08,0.3
4,Milk,"Milk, calcium fortified, whole",11111150,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3

In [40]:
#testing for row checking
food.iloc[0]["Category"]

'Milk'

In [41]:
#making a function that looks at all of the dairy 
def milk():
    return food[(food["Category"].str.contains("Milk"))| 
                    food["Category"].str.contains("milk") |  food["Category"].str.contains("Cheese") | food["Category"].str.contains("Yogurt") | (food["Description"].str.contains("milk")) & (food["Category"] != "Grits") & (food["Category"] != "Rice") & (food["Category"] != "Oatmeal") ]
milk()

,Category,Description,Nutrient Data Bank Number,Alpha Carotene,Beta Carotene,Beta Cryptoxanthin,Carbohydrate,Cholesterol,Choline,Fiber,...,Major Minerals.Phosphorus,Major Minerals.Potassium,Major Minerals.Sodium,Major Minerals.Zinc,Vitamins.Vitamin A - RAE,Vitamins.Vitamin B12,Vitamins.Vitamin B6,Vitamins.Vitamin C,Vitamins.Vitamin E,Vitamins.Vitamin K
0,Milk,"Milk, human",11000000,0,7,0,6.89,14,16.0,0.0,...,14,51,17,0.17,61,0.05,0.011,5.0,0.08,0.3
1,Milk,"Milk, NFS",11100000,0,4,0,4.87,8,17.9,0.0,...,103,157,39,0.42,59,0.56,0.060,0.1,0.03,0.2
2,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
3,Milk,"Milk, low sodium, whole",11111100,0,7,0,4.46,14,16.0,0.0,...,86,253,3,0.38,29,0.36,0.034,0.9,0.08,0.3
4,Milk,"Milk, calcium fortified, whole",11111150,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6869,Horchata beverage,"Horchata beverage, made with milk",92610030,0,2,1,19.66,2,3.6,0.4,...,31,41,9,0.22,5,0.09,0.031,0.0,0.03,0.2
6871,Oatmeal beverage with milk,Oatmeal beverage with milk,92611100,0,3,0,15.49,5,8.3,0.2,...,53,74,18,0.27,14,0.22,0.027,0.0,0.03,0.2
6874,Cornmeal beverage with chocolate milk,Cornmeal beverage with chocolate milk,92613510,0,3,0,20.88,5,9.8,0.4,...,60,97,19,0.32,14,0.19,0.041,0.0,0.04,0.2
7015,Nutritional powder mix (Muscle Milk),Nutritional powder mix (Muscle Milk),95202000,0,0,0,18.50,21,81.6,7.1,...,643,1129,329,7.14,750,3.00,1.000,30.0,7.07,0.5
7058,Cheese as ingredient in sandwiches,Cheese as ingredient in sandwiches,99991400,0,86,5,4.32,90,26.4,0.0,...,604,148,1058,3.05,269,1.54,0.077,0.0,0.71,2.4

In [57]:
#making a Function looking for Things High in Carb
def Carbs():
    newdata = food.drop_duplictes(subset = ["Category"], keep = "first")
    return newdata.sort_values(by ="Carbohydrate")
Carbs()

AttributeError: 'DataFrame' object has no attribute 'drop_duplictes'